FROM golang:1.13-alpine
RUN apk --no-cache add git gcc musl-dev && go get github.com/githubnemo/CompileDaemon

WORKDIR /usr/local/poxy

CMD ["CompileDaemon", "-exclude-dir=.git", "-build=go build -o bin/poxy ./cmd/...", "-command=bin/poxy", \
    "-graceful-kill"]
