version: '3'
services:
  app:
    image: devplayer0/poxy:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/local/poxy
    environment:
      - LOG=TRACE
    ports:
      - 8080:8080
