FROM golang:1.13-alpine as builder
RUN apk --no-cache add gcc musl-dev

WORKDIR /usr/local/poxy
COPY go.* ./
RUN go mod download

COPY . .
RUN go build -ldflags '-s -w' -o bin/ ./cmd/...


FROM alpine:3.11

COPY --from=builder /usr/local/poxy/bin/* /usr/local/bin/

VOLUME "/var/cache/poxy"
ENTRYPOINT ["/usr/local/bin/poxy"]
CMD ["-cache=/var/cache/poxy"]
